PracticaMvcCore2Iniciales/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Models;
using PracticaMvcCore2Iniciales.Repositories;
using System.Security.Claims;
using PracticaMvcCore2Iniciales.Filters;

namespace PracticaMvcCore2Iniciales.Controllers
{
    public class ManagedController : Controller
    {
        public RepositoryUsuarios repo;

        public ManagedController(RepositoryUsuarios repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string email
            , string password)
        {
            Usuario usuario =
                await this.repo.ExisteUsuario(email, password);
            if (usuario != null)
            {
                ClaimsIdentity identity =
               new ClaimsIdentity
               (CookieAuthenticationDefaults.AuthenticationScheme
               , ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim
                    (new Claim(ClaimTypes.Name, usuario.Email));
                identity.AddClaim
                    (new Claim(ClaimTypes.NameIdentifier, usuario.Password.ToString()));
                identity.AddClaim
                    (new Claim("Nombre", usuario.Nombre));
                identity.AddClaim
                    (new Claim("Apellidos", usuario.Aepllidos));
                identity.AddClaim
                    (new Claim("Imagen", usuario.Imagen));
                identity.AddClaim
                        (new Claim("IdUsuario", usuario.IdUsuario.ToString()));
                ClaimsPrincipal user = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , user);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ErrorAcceso()
        {
            return View();
        }

        [AuthorizeUsuarios]
        public IActionResult PerfilUsuario()
        {
            return View();
        }
    }
}

PracticaMvcCore2Iniciales/Controllers/TiendaController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Extensions;
using PracticaMvcCore2Iniciales.Filters;
using PracticaMvcCore2Iniciales.Models;
using PracticaMvcCore2Iniciales.Repositories;

namespace PracticaMvcCore2Iniciales.Controllers
{
    public class TiendaController : Controller
    {
        private RepositoryLibros repo;

        public TiendaController(RepositoryLibros repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Libro> libro = this.repo.GetLibros();
            return View(libro);
        }

        public IActionResult Detalles(int idLibro, int? idCarrito)
        {
            if (idCarrito != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetObject<List<int>>("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                if (carrito.Contains(idCarrito.Value) == false)
                {
                    carrito.Add(idCarrito.Value);
                    HttpContext.Session.SetObject("CARRITO", carrito);
                }
            }
            Libro libro = this.repo.FindLibro(idLibro);
            return View(libro);
        }

        public async Task<IActionResult>
            PaginarGrupoLibros(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            int registros = this.repo.GetNumeroEmpleados();
            List<Libro> lirbos =
                await this.repo.GetGrupoLibrosAsync(posicion.Value);
            ViewData["REGISTROS"] = registros;
            return View(lirbos);
        }

        public IActionResult Carrito(int? idCarrito)
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito == null)
            {
                return View();
            }
            else
            {
                if (idCarrito != null)
                {
                    carrito.Remove(idCarrito.Value);
                    HttpContext.Session.SetObject("CARRITO", carrito);
                }

                List<Libro> productos = this.repo.BuscarProductoCarrito(carrito);
                return View(productos);
            }
        }

        [HttpPost]
        [AuthorizeUsuarios]
        public IActionResult Pedidos(int idLibro)
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            int idCliente = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);
            int cantidad = 1;
            int factura = 1;
            foreach (var item in carrito)
            {
                this.repo.AgregarPedido(idCliente, cantidad, carrito[0], factura);
            }
            HttpContext.Session.Remove("CARRITO");

            return RedirectToAction("MostrarPedidos", new { idcliente = idCliente });

        }

        public IActionResult MostrarPedidos(int idcliente)
        {
            List<Pedido> pedidos = this.repo.MostrarPedidos(idcliente);
            return View(pedidos);
        }
    }
}

PracticaMvcCore2Iniciales/ViewComponents/MenuLibrosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Models;
using PracticaMvcCore2Iniciales.Repositories;

namespace PracticaMvcCore2Iniciales.ViewComponents
{
    public class MenuLibrosViewComponent: ViewComponent
    {
        private RepositoryLibros repo;

        public MenuLibrosViewComponent(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> genero = this.repo.GetGeneros();
            return View(genero);
        }
    }
}

PracticaMvcCore2Iniciales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMvcCore2Iniciales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMvcCore2Iniciales.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMvcCore2Iniciales</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tienda" asp-action="PaginarGrupoLibros">Libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tienda" asp-action="Carrito">Carrito</a>
                        </li>
                        <partial name="_MenuUsuarios" />
                        @await Component.InvokeAsync("MenuLibros")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PracticaMvcCore2Iniciales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaMvcCore2Iniciales/Views/Shared/_MenuUsuarios.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Login">Login</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark"
       asp-controller="Managed"
       asp-action="PerfilUsuario">
            , <span style="color: red">@Context.User.FindFirst("Nombre")?.Value @Context.User.FindFirst("Apellidos")?.Value</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
       asp-controller="Managed"
       asp-action="LogOut">
            LogOut
        </a>
    </li>
}